language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: "NH63AiBlj5OCB53DT2j4map72OJPz/r2wjiykOZ3m/5aZRXxNoGNK9gSy0EDRQtinIzL0j47AymbXoswcBf0RMtLZfTONqeqQMbMrhHb+WmBRVUpmKHNRiKzV+Qg0E+Ob3FKkIW87++qDscGhSonTcToa+3NZiOHPV27xM77kGl4VqDj2/QtcVUCTbwvFcFgcYPnGZuM3+xlM5OR9R0w4Suyhiz6sklPStu0slgQLbbYBl3hcJ8VoY9DoERqCFCYgnLLSqs02UfKEY3Yqbwrc/hp44jiE9Ep0kGV1RQGuzUALlhv49XsLacmDtpSEzdd4L/nxK0218gGgplgW91G99/Aw1i5dNDCaDR+/r/Amw10itNnlzSA6isasDznoSR8JND3K3Rpj0drfW1dgwKing4ceQ9PotkUrIpim9YYwtic7ti4MGPztXZrCdt1vHhj7r2IF11A13bm58fWchyKM/tDWFCo5ZyuhOQoz8yjhTZLDxU7QpuamjHfJHvyjwW/P3Gp7TH9wmWX61mbUt24QXYBP8RF1HVL3GmIBmtU7yS07OuDBWe6tbttIlANWwIEbF+L2L0c466sSuuP7X7kljQwyEOjbldMC6wcOrU1pCBguKDTHCUZbEXDkWG+O8CTeVmZrx7tdJYuuqnUQSTXINtFB1lQ+nMjG7Hy+gyZuhM=
"
  app: istic-20181116
